### ISSUE TITLE
[OAuthToken] 报异常

### ISSUE THREAD

**Issue by coolincy** [dotnetcore/WebApiClient#136]
AddClientCredentialsTokenProvider 添加OAuth认证，调用接口会发生如下异常，发生异常后无法自动恢复，只能重启程序，而且重启后可能正常，也可能继续异常。

`Message:The semaphore has been disposed.
StackTrace:
   at WebApiClientCore.ActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at WebApiClientCore.TaskExtenstions.<>c__DisplayClass4_0`1.<<Handle>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WebApiClientCore.ActionHandleTask`1.<>c__DisplayClass5_0`1.<<WhenCatchAsync>g__newInvoker|0>d.MoveNext()
ExtInfo:
InnerException 1 -- Message:The semaphore has been disposed.
  StackTrace:
     at System.Threading.SemaphoreSlim.CheckDispose()
     at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Threading.SemaphoreSlim.WaitAsync()
     at WebApiClientCore.Extensions.OAuths.TokenProviders.AsyncRoot.LockAsync()
     at WebApiClientCore.Extensions.OAuths.TokenProviders.TokenProvider.GetTokenAsync()
     at WebApiClientCore.Attributes.OAuthTokenAttribute.OnRequestAsync(ApiRequestContext context)
     at WebApiClientCore.ContextInvoker.<>c__DisplayClass3_4.<<BuildRequestHandler>b__9>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at WebApiClientCore.ContextInvoker.<>c__DisplayClass3_3.<<BuildRequestHandler>b__8>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at WebApiClientCore.ContextInvoker.<>c__DisplayClass3_2.<<BuildRequestHandler>b__7>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at WebApiClientCore.ContextInvoker.<>c__DisplayClass3_1.<<BuildRequestHandler>b__6>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at WebApiClientCore.ContextInvoker.<>c__DisplayClass1_0.<<-cctor>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at WebApiClientCore.ActionInvoker`1.InvokeAsync(ApiRequestContext request)
     at WebApiClientCore.ActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)`

**Comment by xljiulang** [comment]
这个是TokenProvider实例被Dispose了，你代码里哪里有如下Dispose代码吗？
```
var tokenProvider = serviceProvider.Get<ITokenProviderFactory>().Create(type);
...
tokenProvider.Dispose()
```

**Comment by coolincy** [comment]
没有操作 tokenProvider , 也没有对注入的对象做显式的 Dispose

**Comment by xljiulang** [comment]
你把如下的代码添加项目，运行和抓取异常看看：
```
class MyClientCredentialsTokenProvider : ClientCredentialsTokenProvider
{
    public MyClientCredentialsTokenProvider(IServiceProvider services)
        : base(services)
    {
    }

    protected override void Dispose(bool disposing)
    {
        var caller = new StackTrace(true).GetFrame(1)?.GetMethod();
        throw new Exception($"此处不应该被触发调用，但被{caller}调用了");
    }
}
```

再把原来的services.AddClientCredentialsTokenProvider<IUserApi>()代码替换为如下

```
var builder = services.AddTokenProvider<IUserApi, MyClientCredentialsTokenProvider>();
services.AddOptions<ClientCredentialsOptions>(builder.Name).Configure(o =>
{
    o.Endpoint = new Uri("http://localhost:5000/api/tokens");
    o.Credentials.Client_id = "clientId";
    o.Credentials.Client_secret = "xxyyzz";
});

```

**Comment by xljiulang** [comment]
更新到 v1.1.3，已[解决在abp下的此问题](https://github.com/dotnetcore/WebApiClient/commit/d66b19b7d7ba40fc1b73f78a4889ff1d8f1436d0)
