### ISSUE TITLE
当地址不存在时，返回的错误有问题，提示未将对象引用到对象实例

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#15]
发生了 System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=WebApiClient
  StackTrace:
   at WebApiClient.Attributes.ApiReturnAttribute.WebApiClient.Interfaces.IApiReturnAttribute.GetTaskResult(ApiActionContext context) in D:\项目\WebApiClient-master\WebApiClient\Attributes\ReturnAttributes\ApiReturnAttribute.cs:line 32
   at WebApiClient.ApiTask.ApiTaskOf`1.<RequestAsync>d__7.MoveNext() in D:\项目\WebApiClient-master\WebApiClient\Internal\ApiTask.cs:line 179
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebApiClient.ApiTask.ApiTaskOf`1.<RequestAsync>d__6.MoveNext() in D:\项目\WebApiClient-master\WebApiClient\Internal\ApiTask.cs:line 129
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Demo.Program.<RunApisAsync3>d__4.MoveNext() in D:\项目\WebApiClient-master\Demo\Program.cs:line 71
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Demo.Program.<RunIUserApi>d__1.MoveNext() in D:\项目\WebApiClient-master\Demo\Program.cs:line 41

**Comment by hzr1348** [comment]
版本1.1.6

**Comment by hzr1348** [comment]
采用github上下载的demo进行测试

**Comment by hzr1348** [comment]
[HttpHost("http://127.0.0.1:50001")] 
    [AutoReturn(EnsureSuccessStatusCode = true)]
    public interface IFileApi : IHttpApiClient
    {
        [HttpGet("/api/v1/ZplFile/Express/{pobid}")]
        ITask<HttpResponseMessage> GetExpressLabelAsync(int pobid);
    }

**Comment by hzr1348** [comment]
当httphost地址不存在时报错

**Comment by hzr1348** [comment]
具体错误代码

**Comment by hzr1348** [comment]
/// <summary>
            /// 执行一次请求
            /// </summary>
            /// <returns></returns>
            private async Task<TResult> RequestAsync()
            {
                var context = new ApiActionContext
                {
                    ApiActionDescriptor = this.apiActionDescriptor,
                    HttpApiConfig = this.httpApiConfig,
                    RequestMessage = new HttpApiRequestMessage { RequestUri = this.httpApiConfig.HttpHost },
                    ResponseMessage = null
                };
                var result = await this.RequestAsync(context);
                return (TResult)result;
            }

**Comment by hzr1348** [comment]
期待返回地址未找到相关信息，比如状态码404

**Comment by hzr1348** [comment]
如果泛型中包含了具体的返回类型，直接返回NULL，或者正确的异常信息

**Comment by hzr1348** [comment]
如果包含具体的返回类型，为NULL时，参考返回值,default(TEntity)

**Comment by xljiulang** [comment]
那你在ApiReturnAttribute的行31下断看看，context.ResponseMessage对象是否为NULL。

**Comment by hzr1348** [comment]
为NULL，我服务的宿主机没开。Response没有返回值

**Comment by hzr1348** [comment]
-		context	{WebApiClient.Contexts.ApiActionContext}	WebApiClient.Contexts.ApiActionContext
+		ApiActionDescriptor	Name = "GetExpress2LabelAsync"	WebApiClient.Contexts.ApiActionDescriptor
+		HttpApiConfig	{WebApiClient.HttpApiConfig}	WebApiClient.HttpApiConfig
+		RequestMessage	{GET /api/v1/ZplFile/Express2/123 HTTP/1.1
Host: 192.168.0.8:50001

}	WebApiClient.HttpApiRequestMessage
+		ResponseMessage	null	System.Net.Http.HttpResponseMessage
+		Tags	Id = null	WebApiClient.Tags
+		tags	Id = null	WebApiClient.Tags

**Comment by hzr1348** [comment]
-		context	{WebApiClient.Contexts.ApiActionContext}	WebApiClient.Contexts.ApiActionContext
+		ApiActionDescriptor	Name = "GetExpress2LabelAsync"	WebApiClient.Contexts.ApiActionDescriptor
+		HttpApiConfig	{WebApiClient.HttpApiConfig}	WebApiClient.HttpApiConfig
+		RequestMessage	{GET /api/v1/ZplFile/Express2/123 HTTP/1.1
Host: 192.168.0.8:50001

}	WebApiClient.HttpApiRequestMessage
+		ResponseMessage	null	System.Net.Http.HttpResponseMessage
+		Tags	Id = null	WebApiClient.Tags
+		tags	Id = null	WebApiClient.Tags

**Comment by yuleyule66** [comment]
@hzr1348  请一次性将问题描述清楚，避免频繁打扰订阅用户。另外请注意一下issue的格式
