### ISSUE TITLE
偶尔抛出异常，原因不明，抛出异常的位置：JsonNetReturnAttribute； System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by wangweinjcn** [dotnetcore/WebApiClient#247]
包的版本：
 <PackageReference Include="WebApiClientCore" Version="2.0.4" />
 <PackageReference Include="WebApiClientCore.Extensions.NewtonsoftJson" Version="2.0.4" />
 <PackageReference Include="WebApiClientCore.Extensions.OAuths" Version="2.0.4" />
代码定义：
 [ServiceName("baseDataServer", "ut")]
 [apiConsoleLog]
 [JsonNetReturn]
 public interface iCommTestApi
 {
   
     /// <summary>
     /// 按条件获取全部数据
     /// </summary>
     /// <param name="queryParam"></param>
     /// <param name="objectName"></param>
     /// <returns></returns>
     [HttpPost("api/dbentityop/allRows/{objectName}/{returnFieldType}")]
     Task<IList<Dictionary<string, object>>> queryRows([JsonContent] baseQueryFormModel queryParam, [PathQuery] string objectName, int returnFieldType = 0);

 }

现象：
偶尔会抛出异常
    System.ObjectDisposedException: Cannot access a disposed object.
    Object name: 'IServiceProvider'.
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
       at WebApiClientCore.Attributes.JsonNetReturnAttribute.SetResultAsync(ApiResponseContext context)
       at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
       at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

**Comment by EzrealJ** [comment]
能否提供一份最小可复现代码？
