### ISSUE TITLE
Autofact + WebApiClient 偶发性发生异常 ObjectDisposedException

### ISSUE THREAD

**Issue by cdpidan** [dotnetcore/WebApiClient#71]
堆栈如下：

```
WebApiClient.HttpApiException: 执行GetOrderCancellationTimeUsingGETAsync出现ObjectDisposedException异常 ---> System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at WebApiClient.Contexts.ApiActionContext.GetService[T]()
   at pidan.ApiClient.Filters.JwellApiActionFilter.OnBeginRequestAsync(ApiActionContext context)
   at WebApiClient.Contexts.ApiActionContext.ExecFiltersAsync(Func`2 funcSelector)
   at WebApiClient.Contexts.ApiActionContext.ExecuteActionAsync[TResult]()
   at WebApiClient.ApiTask`1.InvokeAsync()
```

**Comment by xljiulang** [comment]
你的autofa是怎么配制的？有没有使用WebApiClient的Autofac扩展项目

**Comment by cdpidan** [comment]
![image](https://user-images.githubusercontent.com/8141453/58609213-62495d00-82d9-11e9-843d-2031e5e37d4a.png)
注册的时候使用 WebApiClient.Extensions.DependencyInjection 扩展来注册的，最后在 Startup 转交给 Autofac 
![image](https://user-images.githubusercontent.com/8141453/58609270-9b81cd00-82d9-11e9-992f-50dc35ef3ef9.png)

**Comment by cdpidan** [comment]
最终切换为使用：WebApiClient.Extensions.HttpClientFactory 来注册 IHttpApi ttpApi 来解决的。
