### ISSUE TITLE
有办法处理状态码为204的结果吗？目前是直接报错的

### ISSUE THREAD

**Issue by E2Home** [dotnetcore/WebApiClient#93]
请问，如果我的接口返回的是null，状态码为204，目前框架是直接报错的。有什么好的解决方案吗？比如添加怎么样的过滤器？

**Comment by xljiulang** [comment]
异常详情是什么

**Comment by E2Home** [comment]
2019-11-25 21:23:57.407 +08:00 [ERR] 不支持将ContentType为的内容反序列化为Baison.E3OmniChannel.Inventory.Application.SimpleProductDto
如果实际返回的内容为Xml，请为方法声明XmlReturnAttribute
如果实际返回的内容为Json，请为方法声明JsonReturnAttribute
WebApiClient.ApiReturnNotSupportedExteption: 不支持将ContentType为的内容反序列化为Baison.E3OmniChannel.Inventory.Application.SimpleProductDto
如果实际返回的内容为Xml，请为方法声明XmlReturnAttribute
如果实际返回的内容为Json，请为方法声明JsonReturnAttribute
   at WebApiClient.Attributes.AutoReturnAttribute.GetTaskResult(ApiActionContext context)
   at WebApiClient.Contexts.ApiActionContext.ExecHttpRequestAsync()
   at WebApiClient.Contexts.ApiActionContext.ExecRequestAsync()
   at WebApiClient.Contexts.ApiActionContext.ExecuteActionAsync[TResult]()
   at WebApiClient.Contexts.ApiActionContext.ExecuteActionAsync[TResult]()
   at WebApiClient.ApiTask`1.InvokeAsync()
   at Baison.E3OmniChannel.Inventory.Application.Products.ProductAppService.GetFirstProduct(GetFirstProductInput input) in E:\00 百胜软件\01 Code_ASPNETCore\Order\Inventory.Application\Products\ProductAppService.cs:line 163
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by E2Home** [comment]
![image](https://user-images.githubusercontent.com/2412353/69648026-7cf06900-10a5-11ea-8f30-9173f0bb266f.png)
见Wiki，添加[JsonReturn]特性即可解决。https://github.com/dotnetcore/WebApiClient/wiki/WebApiClient%E5%9F%BA%E7%A1%80
